branch-defaults:
  default:
    environment: fix-a-gram-api-dev
    group_suffix: null
global:
  application_name: fix-a-gram-api
  branch: null
  default_ec2_keyname: fix-a-gram-key-pair
  default_platform: Node.js 14 running on 64bit Amazon Linux 2
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: null
  workspace_type: Application
